# Generated by Django 4.1.4 on 2022-12-20 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_project_name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('onboarded_on', models.CharField(choices=[('nBOL', 'nBOL'), ('BOL', 'BOL')], max_length=5)),
                ('authorisation_preference', models.CharField(max_length=20)),
                ('customer_id', models.CharField(max_length=30)),
                ('h2h_user_id', models.CharField(max_length=20)),
                ('countries_involed', models.CharField(choices=[('MZN', 'Mozambique'), ('KE', 'Kenya'), ('AO', 'Angola')], max_length=20)),
                ('capability_required', models.CharField(choices=[('Account Management', 'Account Management'), ('Payments', 'Payments'), ('Collections', 'Collections')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerComms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sending_channel', models.CharField(choices=[('Public', 'Public'), ('VPN', 'VPN')], max_length=10)),
                ('recieving_channel', models.CharField(choices=[('Public', 'Public'), ('VPN', 'VPN')], max_length=10)),
                ('production_ip', models.GenericIPAddressField()),
                ('test_env_ip', models.GenericIPAddressField()),
                ('dr_env_ip', models.GenericIPAddressField()),
                ('production_port_number', models.IntegerField()),
                ('test_env_port_number', models.IntegerField()),
                ('dr_env_port_number', models.IntegerField()),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.customer')),
            ],
        ),
    ]
