# Generated by Django 4.1.4 on 2022-12-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='capability_required',
            field=models.CharField(choices=[('Payments', 'Payments'), ('Collections', 'Collections'), ('Account Management', 'Account Management')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='countries_involed',
            field=models.CharField(choices=[('AO', 'Angola'), ('KE', 'Kenya'), ('MZN', 'Mozambique')], max_length=20),
        ),
    ]
