# Generated by Django 4.1.4 on 2022-12-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_customer_capability_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='capability_required',
            field=models.CharField(choices=[('Account Management', 'Account Management'), ('Collections', 'Collections'), ('Payments', 'Payments')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='countries_involed',
            field=models.CharField(choices=[('MZN', 'Mozambique'), ('AO', 'Angola'), ('KE', 'Kenya')], max_length=20),
        ),
    ]
