# Generated by Django 4.1.4 on 2022-12-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_customer_capability_required_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercomms',
            old_name='customer_name',
            new_name='customer_project_name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='capability_required',
            field=models.CharField(choices=[('Account Management', 'Account Management'), ('Payments', 'Payments'), ('Collections', 'Collections')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='countries_involed',
            field=models.CharField(choices=[('KE', 'Kenya'), ('AO', 'Angola'), ('MZN', 'Mozambique')], max_length=20),
        ),
    ]
