# Generated by Django 4.1.4 on 2022-12-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_rename_customer_project_name_customercomms_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='capability_required',
            field=models.CharField(choices=[('Account Management', 'Account Management'), ('Payments', 'Payments'), ('Collections', 'Collections')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='countries_involed',
            field=models.CharField(choices=[('KE', 'Kenya'), ('AO', 'Angola'), ('MZN', 'Mozambique')], max_length=20),
        ),
    ]
