# Generated by Django 4.1.4 on 2022-12-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_customercomms_transport_protocol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='capability_required',
            field=models.CharField(choices=[('Account Management', 'Account Management'), ('Collections', 'Collections'), ('Payments', 'Payments')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='countries_involed',
            field=models.CharField(choices=[('AO', 'Angola'), ('KE', 'Kenya'), ('MZN', 'Mozambique')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customercomms',
            name='transport_protocol',
            field=models.CharField(choices=[('SFTP-Push/Pull', 'SFTP-Push/Pull'), ('SFTP-Push/Push', 'SFTP-Push/Push'), ('Connect Direct', 'Connect Direct'), ('SWIFT-File-Act', 'SWIFT-File-Act')], max_length=20),
        ),
    ]
