# Generated by Django 4.1.4 on 2022-12-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_alter_customer_capability_required_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercomms',
            old_name='dr_env_port_number',
            new_name='dr_env_port',
        ),
        migrations.RenameField(
            model_name='customercomms',
            old_name='production_port_number',
            new_name='production_port',
        ),
        migrations.RenameField(
            model_name='customercomms',
            old_name='test_env_port_number',
            new_name='test_env_port',
        ),
        migrations.AlterField(
            model_name='customer',
            name='capability_required',
            field=models.CharField(choices=[('Payments', 'Payments'), ('Account Management', 'Account Management'), ('Collections', 'Collections')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='countries_involed',
            field=models.CharField(choices=[('MZN', 'Mozambique'), ('AO', 'Angola'), ('KE', 'Kenya')], max_length=20),
        ),
    ]
