# Generated by Django 4.1.4 on 2023-01-06 21:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_rename_dr_env_port_number_customercomms_dr_env_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='capability_required',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Collections', 'Collections'), ('Payments', 'Payments'), ('Account Management', 'Account Management')], max_length=40),
        ),
        migrations.AlterField(
            model_name='customer',
            name='countries_involed',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AO', 'Angola'), ('KE', 'Kenya'), ('MZN', 'Mozambique')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='onboarded_on',
            field=models.CharField(choices=[('BOL', 'BOL'), ('nBOL', 'nBOL')], max_length=5),
        ),
    ]
