# Generated by Django 4.1.4 on 2023-01-06 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_alter_customer_capability_required_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='countries_involed',
            new_name='countries_involved',
        ),
    ]
